### ISSUE TITLE
Crash with Arclight on Startup

### ISSUE THREAD

**Issue by MythicalMontie** [dantaeusb-mc/ZetterGallery#23]
Versions:
- arclight-1.16.5-1.0.24-551ec3ff
- forge 36.2.39
- zetter 0.20.2-1.16.5
- zettergallery 0.40-1.16.5

Crash Report: https://mclo.gs/uZqW8C3
Latest Log: https://mclo.gs/JgS1NVv

**Comment by dantaeusb** [comment]
Just notes for the future me:

From Forge Discord:
> that the error that happens when the fancy forge classloader and the regular java classloader try to classload the same class

Interesting error:
```[27Mar2023 17:56:11.579] [main/INFO] [net.minecraftforge.registries.GameData/]: Potentially Dangerous alternative prefix `zetter` for name `painting_merchant_container`, expected `zettergallery`. This could be a intended override, but in most cases indicates a broken mod.```

**Comment by MythicalMontie** [comment]
Just an FYI that this also happens with plain forge servers too, not just hybrids.

**Comment by dantaeusb** [comment]
Hmm, I’ve got it running fine for a while on my Forge server on a stable version of Forge. Anyways, the the issue should be fixed I believe: I was hoping to include a fix in a bigger release soon, but since this issue is severe, I will share a version with the fix in just a few moments.

If that will work, I’ll make it publicly available ASAP.

**Comment by dantaeusb** [comment]
Could you please try again with this version and let me know if that issue still happens https://github.com/dantaeusb-mc/ZetterGallery/releases/tag/0.4.1

**Comment by dantaeusb** [comment]
Actually, I could be wrong, I'm reviewing the logs again and could be a completely different reason, though incorrect usage of registry and hence loading flow could be a cause as well. Anyways, if you'll have a chance to check that patch, that would be great.

**Comment by MythicalMontie** [comment]
Unfortunately still getting the issue! This time I have a lot more mods so I apologize for that, but same crash.

https://mclo.gs/cKa4sBO

**Comment by dantaeusb** [comment]
Thank you very much for the feedback, I think I've figured it out. I will likely fix that tomorrow, and let you know when it's ready to check.

**Comment by dantaeusb** [comment]
Could you please test with the following versions
Zetter: https://github.com/dantaeusb-mc/Zetter/releases/tag/0.20.3-1.16.5
Zetter Gallery: https://github.com/dantaeusb-mc/ZetterGallery/releases/tag/0.4.1-1.16.5-rc

I've reworked overlays so it should not cause that error eanymore + tested on Forge 1.16.5 dedicated server

**Comment by MythicalMontie** [comment]
Success!! Those builds aren't crashing the server anymore.

**Comment by dantaeusb** [comment]
Great! I will make those versions publicly available on CurseForge and Modrinth soon then. Please let me know if you'll face any other problems.
